# -*- coding: utf-8 -*-
"""Riesgo crediticio y optimización.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QyEBgcYrNOBcthVNk5SnOZ5S5rmVD4Y
"""

import pandas as pd
import numpy as np
import xgboost as xgb
import duckdb
import os
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# ==============================================================================
# 1. LA FÁBRICA DE DATOS (Ajustada con SEÑAL real)
# ==============================================================================
class MexicanEconomySimulator:
    def __init__(self, n_clientes=10000):
        self.n_clientes = n_clientes
        np.random.seed(2026)

    def generate_datasets(self, path):
        ids = np.arange(100000, 100000 + self.n_clientes)
        meses = np.random.randint(1, 13, self.n_clientes)
        flag_informal = np.random.binomial(1, 0.55, self.n_clientes)
        ingreso = np.random.normal(20000, 5000, self.n_clientes)

        # AJUSTE: Creamos correlación real para que el modelo tenga qué aprender
        # Probabilidad de impago = Base + Penalización por Informalidad - Crédito al Ingreso
        prob_base = 0.05 + (0.25 * flag_informal) + (0.10 * (ingreso < 15000))
        prob_base = np.clip(prob_base, 0, 1)
        target = np.random.binomial(1, prob_base)

        df_app = pd.DataFrame({
            'ID_CLIENTE': ids,
            'MES_SOLICITUD': meses,
            'FLAG_INFORMAL': flag_informal,
            'INGRESO_REAL_AJUSTADO_MXN': ingreso,
            'MONTO_CREDITO_MXN': np.random.uniform(10000, 100000, self.n_clientes),
            'TARGET': target
        })

        if not os.path.exists(path): os.makedirs(path)
        df_app.to_csv(f"{path}solicitudes_train.csv", index=False)
        print("✅ Datos generados con SEÑAL DE RIESGO (Informalidad -> Default).")

# ==============================================================================
# 2. EL MOTOR DE RIESGO (Arquitectura de Producción)
# ==============================================================================
class RiskEngineMX:
    def __init__(self, base_path):
        self.base_path = base_path
        self.con = duckdb.connect(database=':memory:')
        # Parámetros estándar para evitar overfitting
        self.model = xgb.XGBClassifier(n_estimators=100, learning_rate=0.05, max_depth=3, random_state=42)

    def etl(self):
        query = f"SELECT * FROM read_csv_auto('{self.base_path}solicitudes_train.csv')"
        self.df = self.con.execute(query).df()
        return self.df

    def validate_out_of_time(self, mes_corte=10):
        """Entrena con el pasado y evalúa con el futuro."""
        # 1. Split Temporal
        train_data = self.df[self.df['MES_SOLICITUD'] < mes_corte]
        test_data = self.df[self.df['MES_SOLICITUD'] >= mes_corte]

        features = ['FLAG_INFORMAL', 'INGRESO_REAL_AJUSTADO_MXN', 'MONTO_CREDITO_MXN']
        X_train, y_train = train_data[features], train_data['TARGET']
        X_test, y_test = test_data[features], test_data['TARGET']

        # 2. Entrenamiento
        self.model.fit(X_train, y_train)

        # 3. Métrica Gini (2*AUC - 1)
        probs_test = self.model.predict_proba(X_test)[:, 1]
        auc_test = roc_auc_score(y_test, probs_test)
        gini_test = (2 * auc_test) - 1

        print(f"📈 Gini en periodo OOT (Meses {mes_corte}-12): {gini_test:.2f}")
        return gini_test

    def run_stress_test(self, shock_ingreso=0.20, shock_informalidad=0.15):
        """
        Simula una crisis:
        1. El ingreso real cae un 20% (shock_ingreso).
        2. El 15% de los formales pierden su empleo y pasan a la informalidad.
        """
        print(f"\n🌪️ Iniciando Stress Test (Shock Ingreso: -{shock_ingreso*100}%)")

        # Copiamos los datos del periodo OOT (Meses 10-12) para no alterar los originales
        df_stress = self.df[self.df['MES_SOLICITUD'] >= 10].copy()

        # APLICAR SHOCKS
        # Reducción de ingresos
        df_stress['INGRESO_REAL_AJUSTADO_MXN'] *= (1 - shock_ingreso)

        # Migración a la informalidad (Solo para quienes eran formales)
        mask_formal = df_stress['FLAG_INFORMAL'] == 0
        df_stress.loc[mask_formal, 'FLAG_INFORMAL'] = np.random.binomial(1, shock_informalidad, mask_formal.sum())

        # PREDECIR CON EL MODELO ENTRENADO
        features = ['FLAG_INFORMAL', 'INGRESO_REAL_AJUSTADO_MXN', 'MONTO_CREDITO_MXN']
        X_stress = df_stress[features]
        y_stress = df_stress['TARGET']

        probs_stress = self.model.predict_proba(X_stress)[:, 1]

        # MÉTRICAS DE IMPACTO
        pd_original = self.df[self.df['MES_SOLICITUD'] >= 10]['TARGET'].mean()
        pd_proyectada = probs_stress.mean()
        gini_stress = (2 * roc_auc_score(y_stress, probs_stress)) - 1

        print(f"📉 RESULTADOS DEL ESCENARIO DE CRISIS:")
        print(f"   - Tasa de Default Original: {pd_original*100:.2f}%")
        print(f"   - Tasa de Default Proyectada (Crisis): {pd_proyectada*100:.2f}%")
        print(f"   - Degradación del Gini: {gini_stress:.2f}")

        aumento_riesgo = (pd_proyectada / pd_original) - 1
        print(f"⚠️ El riesgo de la cartera aumentó un {aumento_riesgo*100:.1f}% ante el choque.")

        return gini_stress, aumento_riesgo


class RiskVisualizer:
    def __init__(self, engine):
        self.engine = engine
        self.model = engine.model
        # Usamos el set OOT (futuro) para visualizar el desempeño real
        self.X_test = engine.df[engine.df['MES_SOLICITUD'] >= 10][['FLAG_INFORMAL', 'INGRESO_REAL_AJUSTADO_MXN', 'MONTO_CREDITO_MXN']]
        self.y_test = engine.df[engine.df['MES_SOLICITUD'] >= 10]['TARGET']
        self.probs = self.model.predict_proba(self.X_test)[:, 1]

    def plot_executive_summary(self, tasa_interes=0.30, lgd=0.65):
        # --- GRÁFICA 1: P&L (Lógica de Negocio) ---
        plt.figure(figsize=(12, 6))
        umbrales = np.linspace(0.05, 0.80, 50)
        montos = self.engine.df.loc[self.X_test.index, 'MONTO_CREDITO_MXN'].values
        beneficios = []

        for u in umbrales:
            aprobados = self.probs < u
            ganancia = montos[aprobados & (self.y_test == 0)].sum() * tasa_interes
            perdida = montos[aprobados & (self.y_test == 1)].sum() * lgd
            beneficios.append(ganancia - perdida)

        u_opt = umbrales[np.argmax(beneficios)]

        plt.plot(umbrales, beneficios, color='#2ca02c', lw=3)
        plt.axvline(u_opt, color='red', linestyle='--', label=f'Corte Óptimo: {u_opt*100:.1f}%')
        plt.title('Estrategia de Negocio: Maximización de Utilidad', fontsize=16, fontweight='bold', pad=20)
        plt.xlabel('Score de Riesgo (Probabilidad de Default)')
        plt.ylabel('Beneficio Neto Proyectado ($)')
        plt.legend()
        plt.grid(alpha=0.3)
        plt.show()

        print("\n" + "-"*100 + "\n")

        # --- GRÁFICA 2: SHAP (Explicabilidad) ---
        # SHAP maneja su propia figura, así que le damos libertad total
        explainer = shap.TreeExplainer(self.model)
        shap_values = explainer.shap_values(self.X_test)

        plt.figure(figsize=(12, 8)) # Creamos un lienzo nuevo
        plt.title('Explicabilidad: Principales Drivers de Riesgo', fontsize=16, fontweight='bold', pad=20)

        # 'show=False' permite que podamos personalizar el título antes de mostrar
        shap.summary_plot(shap_values, self.X_test, plot_type="bar", show=False)

        plt.tight_layout()
        plt.show()

        print(f"✅ Reporte Ejecutivo Finalizado.")
        print(f"👉 Punto de corte sugerido para producción: {u_opt*100:.1f}%")

# ==============================================================================
# 3. EJECUCIÓN (El Pipeline final)
# ==============================================================================
PATH_PRODUCCION = './data_bancaria/'

# Instanciar y Generar
simulador = MexicanEconomySimulator(n_clientes=10000)
simulador.generate_datasets(PATH_PRODUCCION)

# Cargar y Entrenar
motor = RiskEngineMX(PATH_PRODUCCION)
motor.etl()

print("\n" + "="*50)
print("🔍 RESULTADOS DEL MODELO EN PRODUCCIÓN")
print("="*50)

gini_final = motor.validate_out_of_time(mes_corte=10)

print("="*50)
if gini_final > 0.30:
    print(f"✅ ÉXITO: Gini de {gini_final:.2f}. El modelo detecta patrones de riesgo.")
else:
    print(f"❌ ALERTA: Gini de {gini_final:.2f}. Revisar calidad de datos.")
print("="*50)

# Ejecutamos el Stress Test
gini_st, riesgo_subida = motor.run_stress_test(shock_ingreso=0.25) # Crisis fuerte

# Visualización y Explicabilidad
visualizador = RiskVisualizer(motor)
visualizador.plot_executive_summary()